CLE-3128: Update packages
yoyowallet/drf-integrations-framework pull request #60
Opened 2024-12-10 16:59 UTC by DelboyJay

- Update packages
- move to ruff and remove black, isort, and flake8

2024-12-11 15:24 UTC, lewis-kori requested changes

2024-12-11 15:24 UTC, lewis-kori commented on .github/workflows/continuous_integration.yml
> +        # python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
It's best to remove the commented-out code in line 41 instead of leaving it here.

2024-12-11 15:24 UTC, lewis-kori commented on .pre-commit-config.yaml
> +    rev: v0.7.2
```suggestion
    rev: v0.8.2
```

Let's use the latest version: https://github.com/astral-sh/ruff/releases/tag/0.8.2

2024-12-11 15:24 UTC, lewis-kori commented on Makefile
>  	poetry env use 3.9
I’ve noticed we frequently use this pattern in our projects, particularly in this variation:

```
.PHONY: deps-clean
deps-clean:
	# Remove the environment and ignore errors if it does not exist.
	poetry env remove 3.12 2>/dev/null || true
	poetry env use 3.12

.PHONY: deps
deps: deps-clean
	poetry install
```

I suggest we either modify it or separate the two commands. The reason is that this approach completely deletes the virtual environment and creates a new one from scratch. In most cases, we only need to update the existing environment with the new dependencies. If someone intends to delete and recreate the environment, they should explicitly run `make deps-clean && make deps`. Coupling these commands seems unnecessary.

2024-12-11 15:24 UTC, lewis-kori commented on drf_integrations/migrations/0001_initial.py
> +                        ),
I think it'd be beneficial to have these as translateable strings.
Given that it's an open-source project. We may run the actual translations now but having the infrastructure in place would go a long way in boosting more adoption for the library.

I understand it's not part of this ticket's scope but something we can put in our roadmap.

2024-12-11 15:24 UTC, lewis-kori commented on drf_integrations/migrations/0001_initial.py
> +                    )
I recommend using the `UniqueConstraint` instead of `unique_together` for better maintainability and future-proofing. As noted in the [Django documentation](https://docs.djangoproject.com/en/4.1/ref/models/options/#unique-together), `unique_together` is marked as obsolete.

2024-12-11 15:24 UTC, lewis-kori commented on ruff.toml
> +indent-style = "space"
tabs or spaces? 😝

2024-12-11 15:24 UTC, lewis-kori commented on setup.py
Did you delete this because we're using poetry to package the library now?

2024-12-11 15:36 UTC, DelboyJay commented on drf_integrations/migrations/0001_initial.py
> +                    )
This is only changing because of ruff I'm not altering anything here for this ticket because that is out of scope.

2024-12-11 15:37 UTC, DelboyJay commented on ruff.toml
> +indent-style = "space"
This is a copy from all the others and spaces are the python standard.

2024-12-12 11:14 UTC, DelboyJay commented on Makefile
>  	poetry env use 3.9
Happy to do this but...
1. if you call `make deps` in your code above it calls `deps-clean` which means it wipes everything and that's how we have always done things.
2. if you want to update to the latest dependant packages (not the top-level ones defined in pypoetry.toml but packages they depend on) you run `poetry  update` and not a `make` command. To update individually top-level packages you must use `poetry add <package>@latest` 

Based on these facts I'm not seeing the problem but to be consistent I'll use the same commands as above.

2025-09-11 11:26 UTC, DelboyJay commented
Dropped in favor of https://github.com/yoyowallet/drf-integrations-framework/pull/56

2025-09-11 11:26 UTC, closed without merging